name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: rull up cleaning
        run: npm uninstall @rollup/rollup-win32-x64-msvc
      - name: install rollup
        run: npm install --save-dev rollup
      - name: remove node module
        run: rm -rf node_modules package-lock.json
      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build
        env:
          CI: false
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: rull up cleaning
        run: npm uninstall @rollup/rollup-win32-x64-msvc
      - name: install rollup
        run: npm install --save-dev rollup
      - name: remove node module
        run: rm -rf node_modules package-lock.json
      - name: Install dependencies
        run: |
          npm install

      - name: Build the React app
        run: npm run build
        env:
          CI: false

      - name: Deploy to Nginx
        run: sudo cp -r dist/* /var/www/html
      - name: Restart Nginx
        run: sudo systemctl restart nginx
